package bean;
// Generated 31/07/2024 10:37:21 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClienteLgo generated by hbm2java
 */
@Entity
@Table(name="cliente_lgo"
    ,catalog="db_luan_goncalves"
)
public class ClienteLgo  implements java.io.Serializable {


     private int idclienteLgo;
     private String nomeLgo;
     private String cpfLgo;
     private String rgLgo;
     private String generoLgo;
     private String celularLgo;
     private Date dataDeNascimentoLgo;
     private String emailLgo;
     private String cepLgo;
     private String telefoneLgo;
     private String cidadeLgo;
     private String bairroLgo;
     private String estadoLgo;
     private String ruaLgo;
     private String numeroLgo;
     private String estadoCivilLgo;

    public ClienteLgo() {
    }

	
    public ClienteLgo(int idclienteLgo) {
        this.idclienteLgo = idclienteLgo;
    }
    public ClienteLgo(int idclienteLgo, String nomeLgo, String cpfLgo, String rgLgo, String generoLgo, String celularLgo, Date dataDeNascimentoLgo, String emailLgo, String cepLgo, String telefoneLgo, String cidadeLgo, String bairroLgo, String estadoLgo, String ruaLgo, String numeroLgo, String estadoCivilLgo) {
       this.idclienteLgo = idclienteLgo;
       this.nomeLgo = nomeLgo;
       this.cpfLgo = cpfLgo;
       this.rgLgo = rgLgo;
       this.generoLgo = generoLgo;
       this.celularLgo = celularLgo;
       this.dataDeNascimentoLgo = dataDeNascimentoLgo;
       this.emailLgo = emailLgo;
       this.cepLgo = cepLgo;
       this.telefoneLgo = telefoneLgo;
       this.cidadeLgo = cidadeLgo;
       this.bairroLgo = bairroLgo;
       this.estadoLgo = estadoLgo;
       this.ruaLgo = ruaLgo;
       this.numeroLgo = numeroLgo;
       this.estadoCivilLgo = estadoCivilLgo;
    }
   
     @Id 

    
    @Column(name="idcliente_lgo", unique=true, nullable=false)
    public int getIdclienteLgo() {
        return this.idclienteLgo;
    }
    
    public void setIdclienteLgo(int idclienteLgo) {
        this.idclienteLgo = idclienteLgo;
    }

    
    @Column(name="nome_lgo", length=50)
    public String getNomeLgo() {
        return this.nomeLgo;
    }
    
    public void setNomeLgo(String nomeLgo) {
        this.nomeLgo = nomeLgo;
    }

    
    @Column(name="cpf_lgo", length=14)
    public String getCpfLgo() {
        return this.cpfLgo;
    }
    
    public void setCpfLgo(String cpfLgo) {
        this.cpfLgo = cpfLgo;
    }

    
    @Column(name="rg_lgo", length=8)
    public String getRgLgo() {
        return this.rgLgo;
    }
    
    public void setRgLgo(String rgLgo) {
        this.rgLgo = rgLgo;
    }

    
    @Column(name="genero_lgo", length=20)
    public String getGeneroLgo() {
        return this.generoLgo;
    }
    
    public void setGeneroLgo(String generoLgo) {
        this.generoLgo = generoLgo;
    }

    
    @Column(name="celular_lgo", length=12)
    public String getCelularLgo() {
        return this.celularLgo;
    }
    
    public void setCelularLgo(String celularLgo) {
        this.celularLgo = celularLgo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_de_nascimento_lgo", length=10)
    public Date getDataDeNascimentoLgo() {
        return this.dataDeNascimentoLgo;
    }
    
    public void setDataDeNascimentoLgo(Date dataDeNascimentoLgo) {
        this.dataDeNascimentoLgo = dataDeNascimentoLgo;
    }

    
    @Column(name="email_lgo", length=50)
    public String getEmailLgo() {
        return this.emailLgo;
    }
    
    public void setEmailLgo(String emailLgo) {
        this.emailLgo = emailLgo;
    }

    
    @Column(name="cep_lgo", length=8)
    public String getCepLgo() {
        return this.cepLgo;
    }
    
    public void setCepLgo(String cepLgo) {
        this.cepLgo = cepLgo;
    }

    
    @Column(name="telefone_lgo", length=8)
    public String getTelefoneLgo() {
        return this.telefoneLgo;
    }
    
    public void setTelefoneLgo(String telefoneLgo) {
        this.telefoneLgo = telefoneLgo;
    }

    
    @Column(name="cidade_lgo", length=30)
    public String getCidadeLgo() {
        return this.cidadeLgo;
    }
    
    public void setCidadeLgo(String cidadeLgo) {
        this.cidadeLgo = cidadeLgo;
    }

    
    @Column(name="bairro_lgo", length=30)
    public String getBairroLgo() {
        return this.bairroLgo;
    }
    
    public void setBairroLgo(String bairroLgo) {
        this.bairroLgo = bairroLgo;
    }

    
    @Column(name="estado_lgo", length=20)
    public String getEstadoLgo() {
        return this.estadoLgo;
    }
    
    public void setEstadoLgo(String estadoLgo) {
        this.estadoLgo = estadoLgo;
    }

    
    @Column(name="rua_lgo", length=30)
    public String getRuaLgo() {
        return this.ruaLgo;
    }
    
    public void setRuaLgo(String ruaLgo) {
        this.ruaLgo = ruaLgo;
    }

    
    @Column(name="numero_lgo", length=5)
    public String getNumeroLgo() {
        return this.numeroLgo;
    }
    
    public void setNumeroLgo(String numeroLgo) {
        this.numeroLgo = numeroLgo;
    }

    
    @Column(name="estadoCivil_lgo", length=20)
    public String getEstadoCivilLgo() {
        return this.estadoCivilLgo;
    }
    
    public void setEstadoCivilLgo(String estadoCivilLgo) {
        this.estadoCivilLgo = estadoCivilLgo;
    }




}


