package bean;
// Generated 31/07/2024 10:37:21 by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProdutosLgo generated by hbm2java
 */
@Entity
@Table(name="produtos_lgo"
    ,catalog="db_luan_goncalves"
)
public class ProdutosLgo  implements java.io.Serializable {


     private int idprodutosLgo;
     private double precoLgo;
     private String tipoLgo;
     private String descricaoLgo;
     private int quantidadeLgo;

    public ProdutosLgo() {
    }

	
    public ProdutosLgo(int idprodutosLgo) {
        this.idprodutosLgo = idprodutosLgo;
    }
    public ProdutosLgo(int idprodutosLgo, double precoLgo, String tipoLgo, String descricaoLgo, int quantidadeLgo) {
       this.idprodutosLgo = idprodutosLgo;
       this.precoLgo = precoLgo;
       this.tipoLgo = tipoLgo;
       this.descricaoLgo = descricaoLgo;
       this.quantidadeLgo = quantidadeLgo;
    }
   
     @Id 

    
    @Column(name="idprodutos_lgo", unique=true, nullable=false)
    public int getIdprodutosLgo() {
        return this.idprodutosLgo;
    }
    
    public void setIdprodutosLgo(int idprodutosLgo) {
        this.idprodutosLgo = idprodutosLgo;
    }

    
    @Column(name="preco_lgo", precision=10)
    public double getPrecoLgo() {
        return this.precoLgo;
    }
    
    public void setPrecoLgo(double precoLgo) {
        this.precoLgo = precoLgo;
    }

    
    @Column(name="tipo_lgo", length=10)
    public String getTipoLgo() {
        return this.tipoLgo;
    }
    
    public void setTipoLgo(String tipoLgo) {
        this.tipoLgo = tipoLgo;
    }

    
    @Column(name="descricao_lgo", length=50)
    public String getDescricaoLgo() {
        return this.descricaoLgo;
    }
    
    public void setDescricaoLgo(String descricaoLgo) {
        this.descricaoLgo = descricaoLgo;
    }

    
    @Column(name="quantidade_lgo")
    public int getQuantidadeLgo() {
        return this.quantidadeLgo;
    }
    
    public void setQuantidadeLgo(int quantidadeLgo) {
        this.quantidadeLgo = quantidadeLgo;
    }




}


