package bean;
// Generated 31/07/2024 10:37:21 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuariosLgo generated by hbm2java
 */
@Entity
@Table(name="usuarios_lgo"
    ,catalog="db_luan_goncalves"
)
public class UsuariosLgo  implements java.io.Serializable {


     private int idusuariosLgo;
     private String nomeLgo;
     private String apelidoLgo;
     private String cpfLgo;
     private Date dataDeNascimentoLgo;
     private String senhaLgo;
     private int nivelLgo;
     private String ativarLgo;

    public UsuariosLgo() {
    }

	
    public UsuariosLgo(int idusuariosLgo) {
        this.idusuariosLgo = idusuariosLgo;
    }
    public UsuariosLgo(int idusuariosLgo, String nomeLgo, String apelidoLgo, String cpfLgo, Date dataDeNascimentoLgo, String senhaLgo, int nivelLgo, String ativarLgo) {
       this.idusuariosLgo = idusuariosLgo;
       this.nomeLgo = nomeLgo;
       this.apelidoLgo = apelidoLgo;
       this.cpfLgo = cpfLgo;
       this.dataDeNascimentoLgo = dataDeNascimentoLgo;
       this.senhaLgo = senhaLgo;
       this.nivelLgo = nivelLgo;
       this.ativarLgo = ativarLgo;
    }
   
     @Id 

    
    @Column(name="idusuarios_lgo", unique=true, nullable=false)
    public int getIdusuariosLgo() {
        return this.idusuariosLgo;
    }
    
    public void setIdusuariosLgo(int idusuariosLgo) {
        this.idusuariosLgo = idusuariosLgo;
    }

    
    @Column(name="nome_lgo", length=50)
    public String getNomeLgo() {
        return this.nomeLgo;
    }
    
    public void setNomeLgo(String nomeLgo) {
        this.nomeLgo = nomeLgo;
    }

    
    @Column(name="apelido_lgo", length=10)
    public String getApelidoLgo() {
        return this.apelidoLgo;
    }
    
    public void setApelidoLgo(String apelidoLgo) {
        this.apelidoLgo = apelidoLgo;
    }

    
    @Column(name="cpf_lgo", length=14)
    public String getCpfLgo() {
        return this.cpfLgo;
    }
    
    public void setCpfLgo(String cpfLgo) {
        this.cpfLgo = cpfLgo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_de_nascimento_lgo", length=10)
    public Date getDataDeNascimentoLgo() {
        return this.dataDeNascimentoLgo;
    }
    
    public void setDataDeNascimentoLgo(Date dataDeNascimentoLgo) {
        this.dataDeNascimentoLgo = dataDeNascimentoLgo;
    }

    
    @Column(name="senha_lgo", length=15)
    public String getSenhaLgo() {
        return this.senhaLgo;
    }
    
    public void setSenhaLgo(String senhaLgo) {
        this.senhaLgo = senhaLgo;
    }

    
    @Column(name="nivel_lgo")
    public int getNivelLgo() {
        return this.nivelLgo;
    }
    
    public void setNivelLgo(int nivelLgo) {
        this.nivelLgo = nivelLgo;
    }

    
    @Column(name="ativar_lgo", length=1)
    public String getAtivarLgo() {
        return this.ativarLgo;
    }
    
    public void setAtivarLgo(String ativarLgo) {
        this.ativarLgo = ativarLgo;
    }




}


