 package bean;
// Generated 31/07/2024 10:37:21 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendaLgo generated by hbm2java
 */
@Entity
@Table(name="venda_lgo"
    ,catalog="db_luan_goncalves"
)
public class VendaLgo  implements java.io.Serializable {


     private int idvendaLgo;
     private int idcliente;
     private int idvendedor;
     private Date dataVenda;
     private String total;

    public VendaLgo() {
    }

	
    public VendaLgo(int idvendaLgo) {
        this.idvendaLgo = idvendaLgo;
    }
    public VendaLgo(int idvendaLgo, int idcliente, int idvendedor, Date dataVenda, String total) {
       this.idvendaLgo = idvendaLgo;
       this.idcliente = idcliente;
       this.idvendedor = idvendedor;
       this.dataVenda = dataVenda;
       this.total = total;
    }
   
     @Id 

    
    @Column(name="idvenda_lgo", unique=true, nullable=false)
    public int getIdvendaLgo() {
        return this.idvendaLgo;
    }
    
    public void setIdvendaLgo(int idvendaLgo) {
        this.idvendaLgo = idvendaLgo;
    }

    
    @Column(name="idcliente")
    public int getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }

    
    @Column(name="idvendedor")
    public int getIdvendedor() {
        return this.idvendedor;
    }
    
    public void setIdvendedor(int idvendedor) {
        this.idvendedor = idvendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataVenda", length=10)
    public Date getDataVenda() {
        return this.dataVenda;
    }
    
    public void setDataVenda(Date dataVenda) {
        this.dataVenda = dataVenda;
    }

    
    @Column(name="total", length=51)
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }




}


