 package bean;
// Generated 31/07/2024 10:37:21 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendedorLgo generated by hbm2java
 */
@Entity
@Table(name="vendedor_lgo"
    ,catalog="db_luan_goncalves"
)
public class VendedorLgo  implements java.io.Serializable {


     private int idvendedorLgo;
     private String nomeLgo;
     private String cpfLgo;
     private Date dataDeNascimentoLgo;
     private String senhaLgo;

    public VendedorLgo() {
    }

	
    public VendedorLgo(int idvendedorLgo) {
        this.idvendedorLgo = idvendedorLgo;
    }
    public VendedorLgo(int idvendedorLgo, String nomeLgo, String cpfLgo, Date dataDeNascimentoLgo, String senhaLgo) {
       this.idvendedorLgo = idvendedorLgo;
       this.nomeLgo = nomeLgo;
       this.cpfLgo = cpfLgo;
       this.dataDeNascimentoLgo = dataDeNascimentoLgo;
       this.senhaLgo = senhaLgo;
    }
   
     @Id 

    
    @Column(name="idvendedor_lgo", unique=true, nullable=false)
    public int getIdvendedorLgo() {
        return this.idvendedorLgo;
    }
    
    public void setIdvendedorLgo(int idvendedorLgo) {
        this.idvendedorLgo = idvendedorLgo;
    }

    
    @Column(name="nome_lgo", length=50)
    public String getNomeLgo() {
        return this.nomeLgo;
    }
    
    public void setNomeLgo(String nomeLgo) {
        this.nomeLgo = nomeLgo;
    }

    
    @Column(name="cpf_lgo", length=14)
    public String getCpfLgo() {
        return this.cpfLgo;
    }
    
    public void setCpfLgo(String cpfLgo) {
        this.cpfLgo = cpfLgo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_de_nascimento_lgo", length=10)
    public Date getDataDeNascimentoLgo() {
        return this.dataDeNascimentoLgo;
    }
    
    public void setDataDeNascimentoLgo(Date dataDeNascimentoLgo) {
        this.dataDeNascimentoLgo = dataDeNascimentoLgo;
    }

    
    @Column(name="senha_lgo", length=15)
    public String getSenhaLgo() {
        return this.senhaLgo;
    }
    
    public void setSenhaLgo(String senhaLgo) {
        this.senhaLgo = senhaLgo;
    }




}


